-- RotaOS: execute este arquivo no SQL Editor do projeto Supabase oficial.

create table if not exists public.service_orders (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  external_id text not null,
  internal_id text,
  address text not null default '',
  neighborhood text not null default '',
  region text not null default '',
  requested_at timestamptz,
  service text not null default 'Passeio',
  service_code text not null check (service_code in ('S025', 'S200 X', 'S201 X')),
  detail text not null default '',
  sync_state text not null default 'new' check (sync_state in ('new','updated','complaint','reviewed','not_seen','archived')),
  complaint_count integer not null default 0 check (complaint_count >= 0),
  source_hash text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  changed_at timestamptz,
  latest_complaint_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, external_id)
);

create index if not exists service_orders_owner_state_idx on public.service_orders (owner_id, sync_state);
create index if not exists service_orders_owner_neighborhood_idx on public.service_orders (owner_id, neighborhood);
create index if not exists service_orders_owner_last_seen_idx on public.service_orders (owner_id, last_seen_at desc);
create index if not exists service_orders_owner_requested_idx on public.service_orders (owner_id, requested_at desc);
create index if not exists service_orders_owner_complaints_idx on public.service_orders (owner_id, complaint_count desc, latest_complaint_at desc);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  service_order_id bigint not null references public.service_orders(id) on delete cascade,
  event_type text not null check (event_type in ('new','updated','complaint')),
  previous_hash text,
  current_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  team_key text not null,
  name text not null,
  color text not null default '#7457d9',
  active boolean not null default true,
  services jsonb not null default '[]'::jsonb,
  capacity integer not null default 6 check (capacity between 1 and 50),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, team_key)
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  captured_count integer not null default 0,
  new_count integer not null default 0,
  changed_count integer not null default 0,
  unchanged_count integer not null default 0,
  complaint_count integer not null default 0,
  created_at timestamptz not null default now()
);

create or replace function public.rotaos_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rotaos_order_updated_at on public.service_orders;
create trigger rotaos_order_updated_at
before update on public.service_orders
for each row execute function public.rotaos_set_updated_at();

drop trigger if exists rotaos_team_updated_at on public.teams;
create trigger rotaos_team_updated_at
before update on public.teams
for each row execute function public.rotaos_set_updated_at();

create or replace function public.rotaos_track_order_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.order_events (owner_id, service_order_id, event_type, current_hash)
    values (new.owner_id, new.id, 'new', new.source_hash);
  elsif old.source_hash is distinct from new.source_hash then
    insert into public.order_events (owner_id, service_order_id, event_type, previous_hash, current_hash)
    values (
      new.owner_id,
      new.id,
      case when new.sync_state = 'complaint' then 'complaint' else 'updated' end,
      old.source_hash,
      new.source_hash
    );
  end if;
  return new;
end;
$$;

drop trigger if exists rotaos_order_change on public.service_orders;
create trigger rotaos_order_change
after insert or update on public.service_orders
for each row execute function public.rotaos_track_order_change();

alter table public.service_orders enable row level security;
alter table public.order_events enable row level security;
alter table public.teams enable row level security;
alter table public.sync_runs enable row level security;

drop policy if exists "orders_owner_all" on public.service_orders;
drop policy if exists "events_owner_all" on public.order_events;
drop policy if exists "teams_owner_all" on public.teams;
drop policy if exists "sync_runs_owner_all" on public.sync_runs;

create policy "orders_owner_all" on public.service_orders for all to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "events_owner_all" on public.order_events for all to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "teams_owner_all" on public.teams for all to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy "sync_runs_owner_all" on public.sync_runs for all to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());
