create table if not exists public.file_import_orders (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  external_id text not null,
  account_code text,
  address text not null default '',
  neighborhood text not null default '',
  complement text,
  requested_at timestamptz,
  service_type text not null default '',
  observation text not null default '',
  source_hash text not null default '',
  file_name text not null default '',
  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, external_id)
);

create index if not exists file_import_orders_owner_requested_idx on public.file_import_orders (owner_id, requested_at desc);

drop trigger if exists rotaos_file_import_order_updated_at on public.file_import_orders;
create trigger rotaos_file_import_order_updated_at
before update on public.file_import_orders
for each row execute function public.rotaos_set_updated_at();

alter table public.file_import_orders enable row level security;

drop policy if exists "file_import_orders_owner_all" on public.file_import_orders;
create policy "file_import_orders_owner_all" on public.file_import_orders for all to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());
